### ISSUE TITLE
[.NET 8] The type or namespace name 'ManualLogSource' could not be found

### ISSUE THREAD

**Issue by p4nu** [BepInEx/BepInEx.Templates#15]
While following the tutorial of writing a basic plugin and running `dotnet build` with no edits to Plugin.cs I get an error:

```
error CS0246: The type or namespace name 'ManualLogSource' could not be found (are you missing a using directive 
 or an assembly reference?) [C:\Program Files (x86)\Steam\steamapps\common\Timberborn\BepInEx\plugins\MyFirs 
tPlugin\MyFirstPlugin.csproj]
```

.NET version: 8.0.300
Template version: 2.0.0-be.3

## How to reproduce

1. Create a project using this command:
`dotnet new bepinex5plugin -n MyFirstPlugin -T netstandard2.1 -U 2023.1.20`

2. Add referencing game libraries:
`dotnet add package Timberborn.GameLibs --version 0.5.7-r.0`

3. Run `dotnet build`

**Comment by PhantomGamers** [comment]
fixed in #16
