### ISSUE TITLE
https://nuget.bepinex.dev/v3/index.json (Error code 522)

### ISSUE THREAD

**Issue by dhtpdud** [BepInEx/BepInEx.Templates#19]
![image](https://github.com/user-attachments/assets/5fc3f0aa-3bb2-4477-901b-0bd4a0a28cad)

I can't access the package source right now. Is there something wrong?

**Comment by ManlyMarco** [comment]
VPS is temporarily down because of a provider issue.

**Comment by dhtpdud** [comment]
I see. Thank you.

Issue resolved
