### ISSUE TITLE
Package does not exist

### ISSUE THREAD

**Issue by Shillersan** [BepInEx/BepInEx.Templates#9]
```
An update for template package 'BepInEx.Templates::2.0.0-be.1' is available.
To update the package use:
   dotnet new --install BepInEx.Templates::2.0.0-be.2
```

If I run I get error:

`BepInEx.Templates::2.0.0-be.2 could not be installed, the package does not exist.`

**Comment by Xilophor** [comment]
Make sure you are targeting the BepInEx nuget source with `--nuget-source https://nuget.bepinex.dev/v3/index.json`.
